name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    strategy:
      fail-fast: false

      matrix:
        os: [macos, ubuntu]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: .ubpm
          key: ${{ hashFiles('dependencies.cmake') }}-${{ matrix.os }}

      - name: Set GCC version on Ubuntu
        if: matrix.os == 'ubuntu'
        run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - uses: friendlyanon/ubpm@pre-v3

      - name: Configure
        run: cmake -S tests -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run
        working-directory: build
        run: ctest --output-on-failure -C Release
